- label: Introduction
  link: /

- label: Compte utilisateur
  items:
    - label: Création
      link: /compte/creation

- label: Courriel
  items:
    - label: Configuration
      link: /courriel/configuration
