- label: Introduction
  link: /

- label: Compte utilisateur
  items:
    - label: Création
      link: /account/creation
    - label: Gestion
      link: /account/manage

- label: Tenoco Mail
  items:
    - label: Présentation
      link: /mail/about
    - label: Configuration
      link: /mail/configuration

- label: Tenoco Chat
  items:
    - label: Présentation
      link: /chat/about
    - label: Clients
      link: /chat/clients
    - label: Configuration
      link: /chat/configuration

- label: Tenoco Social
  items:
    - label: Présentation
      link: /social/about

- label: Tenoco Meet
  items:
    - label: Présentation
      link: /meet/about
